name: Build OpenUtau iOS
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install MAUI Workload
        run: dotnet workload install ios
      - name: Restore dependencies
        run: dotnet restore OpenUtauMobile.sln
      - name: Build iOS App
        run: |
          dotnet build OpenUtauMobile.sln -f net9.0-ios -c Release /p:BuildIpa=true /p:CodesignKey="-" /p:CodesignProvision="-"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtau-iOS-IPA
          path: |
            **/bin/Release/net9.0-ios/publish/*.ipa
            **/bin/Release/net9.0-ios/*.app
