name: Build OpenUtau iOS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI iOS workload
        run: dotnet workload install maui-ios

      - name: Restore dependencies
        run: dotnet restore -p:TargetFramework=net9.0-ios OpenUtauMobile.sln

      - name: Build IPA
        run: dotnet publish OpenUtauMobile/OpenUtauMobile.csproj -f net9.0-ios -c Debug -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:TargetFrameworks=net9.0-ios -p:CodesignKey="-" -p:CodesignProvision="-" -p:Nullable=disable -p:CheckForOverflowUnderflow=false -p:TreatWarningsAsErrors=false -p:NoWarn=CS8600,CS8601,CS8602,CS8603,CS8604,CS8618,CS8625,CS0108

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtau-iOS-IPA
          path: OpenUtauMobile/bin/Debug/net9.0-ios/ios-arm64/publish/*.ipa
